[sources]
api_secret_key = ""
table_ids = ["g...2", "d...j", "j...K"]
table_names = ["Customer Information", "Item Master", "Lot Inventory"]
instance_url = "{...}.tulip.co"

[destination.postgres.credentials]
database = ""
username = ""
password = ""
host = ""
port = 5432
connect_timeout = 15

[destination.filesystem]
bucket_url = "s3://[your_bucket_name]" # replace with your bucket name,

[destination.filesystem.credentials]
aws_access_key_id = "please set me up!" # copy the access key here
aws_secret_access_key = "please set me up!" # copy the secret access key here
