[sources]
api_secret_key = ""
table_ids = ["g...2", "d...j", "j...K"]
table_names = ["Customer Information", "Item Master", "Lot Inventory"]
instance_url = "{...}.tulip.co"

[destination.postgres.credentials]
database = ""
username = ""
password = ""
host = ""
port = 5432
connect_timeout = 15
